language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
install:
- npm install
script:
- if [[ $TRAVIS_BRANCH == 'master' ]]; then npm run build; fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
